# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 120ee1d4a202fc9e6eb42c667c1193af7356a699affe2cdf238a1df86f9cf1d6bda867b6341daa8c169df4f702df58f30c52a70f96fd951e5ee939e61d6b0580

test:
  secret_key_base: f8a00ebbadd2f5bdd8c23dac75768ea7f68b81a745e83fdd7ede457c08d0388cfb4e5041051c2d6585c9afa588bf23bb25da3e143f19a265df62e597bbf8896a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
